---
title: "ames_housing"
format: html
---

## ames housing data


* loading data
```{r}
library(modeldata)
data(ames)

dim(ames)

```

```{r , message=FALSE}

library(tidymodels)
tidymodels_prefer()
```

```{r}
central_tendency <- data.frame(values = c(min(ames$Sale_Price),
                                   max(ames$Sale_Price),
                                   mean(ames$Sale_Price),
                                   median(ames$Sale_Price)),
                               labled = c("Min", "Max","Mean",
                                          "Median"))

ggplot(ames, aes(x = Sale_Price)) + 
  geom_histogram(bins = 50, col= "white") + 
  geom_vline(data = central_tendency, 
             aes(xintercept = values, color = labled,
             linetype = labled), linewidth = 1) +
  scale_x_log10() + geom_density()
```

```{r}
ames <- ames %>% mutate(Sale_Price = log10(Sale_Price))
```

```{r}
set.seed(502)

ames_split <- initial_split(ames, prop = 0.8, 
                           strata = Sale_Price)
ames_train <- training(ames_split)
ames_test <- testing(ames_split)
```

```{r}
lm_model <- linear_reg() %>% set_engine("lm")
lm_model
```

```{r}
lm_wflow <- workflow() %>% 
  add_model(lm_model) %>% 
  add_formula(Sale_Price ~ Longitude + Latitude)

lm_wflow
```

```{r}
lm_fit <- fit(lm_wflow, ames_train)
lm_fit

predict(lm_fit, ames_test %>% slice(1:3))
```

```{r}
lm_fit %>% update_formula(Sale_Price ~ Longitude)
```

```{r}
lm_wflow <- lm_wflow %>% remove_formula() %>% 
  add_variables(outcome = Sale_Price, predictors = c(Longitude, Latitude))

lm_wflow
```

```{r}
library(tidymodels)
data(ames)
ames <- mutate(ames, Sale_Price = log10(Sale_Price))

set.seed(502)
ames_split <- initial_split(ames, prop = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)

ames_rec <- 
  recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type + 
           Latitude + Longitude, data = ames_train) %>%
  step_log(Gr_Liv_Area, base = 10) %>% 
  step_other(Neighborhood, threshold = 0.01) %>% 
  step_dummy(all_nominal_predictors()) %>% 
  step_interact( ~ Gr_Liv_Area:starts_with("Bldg_Type_") ) %>% 
  step_ns(Latitude, Longitude, deg_free = 20)
  
lm_model <- linear_reg() %>% set_engine("lm")

lm_wflow <- 
  workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(ames_rec)

lm_fit <- fit(lm_wflow, ames_train)
```




